version: '3.7'
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
  web:
    build: 
      context: .
    # command: python manage.py runserver 8000
    volumes:
      - ./media/:/media
      - ./static/:/static
      - ./:/app
    ports:
      - 8000:8000
    entrypoint: ./entrypoint.sh
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  media:
  static:
  postgres_data: